[package]
name = "fce-sqlite-connector"
version = "0.2.0"
license = "Apache-2.0/MIT"
authors = [
    "Daniel Dulaney <ddy@vitronic.com>",
    "Ivan Stankovic <pokemon@fly.srk.fer.hr>",
    "Ivan Ukhov <ivan.ukhov@gmail.com>",
    "Jake Kerr <kodafox@gmail.com>",
    "Jayson Reis <santosdosreis@gmail.com>",
    "Pierre Krieger <pierre.krieger1708@gmail.com>",
    "Sean Klein <seanmarionklein@gmail.com>",
    "Sophie Tauchert <999eagle@999eagle.moe>",
    "Tomoki Aonuma <uasi@uasi.jp>",
    "Yorhel <git@yorhel.nl>",
]
description = "The package provides an interface to SQLite."
documentation = "https://docs.rs/sqlite"
homepage = "https://github.com/stainless-steel/sqlite"
repository = "https://github.com/stainless-steel/sqlite"
readme = "README.md"
categories = ["api-bindings", "database"]
keywords = ["database"]

[lib]
name = "fce_sqlite_connector"
path = "src/lib.rs"

[[bin]]
name = "wit_generator"
path = "src/wit_generator.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[dependencies]
fluence = "0.4.2"

[dev-dependencies]
temporary = "0.6"
