[package]
name = "sqlite"
version = "0.21.0"
license = "Apache-2.0/MIT"
authors = [
  "Ivan Stankovic <pokemon@fly.srk.fer.hr>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
  "Jake Kerr <kodafox@gmail.com>",
  "Tomoki Aonuma <uasi@uasi.jp>",
]
description = "The package provides an interface to SQLite."
documentation = "https://stainless-steel.github.io/sqlite"
homepage = "https://github.com/stainless-steel/sqlite"
repository = "https://github.com/stainless-steel/sqlite"

[features]
default = ["standard"]

standard = ["sqlite3-sys/standard"]
sqlcipher = ["sqlite3-sys/sqlcipher"]

[dependencies]
libc = "0.2"

[dependencies.sqlite3-sys]
version = "0.9"
default-features = false

[dev-dependencies]
temporary = "0.5"
